version: '2'
volumes:
  db:
    driver:
      local
services:
  app:
    image: node:10.15.3
    environment:
      NODE_ENV: development
      PORT: 8080
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: tiptop123
      MYSQL_DATABASE: ledger
      REDIS_HOST: redis
      REDIS_PORT: 6379
    command: [ "npm", "run", "start:dev" ]
    working_dir: /app
    ports:
        - 8080:8080
    volumes:
     - "./:/app"
     - "./logs:/root/.npm/_logs"
  redis:
    image: redis:5.0.4
    ports:
    - "6379:6379"
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: tiptop123
      MYSQL_DATABASE: fieldnation
      MYSQL_USER: fieldnation
      MYSQL_PASSWORD: tiptop123
    volumes:
    - "./data:/docker-entrypoint-initdb.d"
    - "db:/var/lib/mysql"
    command: mysqld --sql-mode=NO_ENGINE_SUBSTITUTION --innodb-buffer-pool-size=2147483648 --innodb-flush-method=O_DIRECT --innodb-flush-log-at-trx-commit=2
    ports:
    - "3306:3306"