version: '2'
volumes:
  db:
    driver:
      local
services:
  app:
    image: node:10.15.3
    links:
    - db
    - redis
    environment:
      NODE_ENV: development
      PORT: 8080
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: tiptop123
      MYSQL_DATABASE: ledger
      REDIS_HOST: redis
      REDIS_PORT: 6379
    command: [ "npm", "run", "start:dev" ]
    working_dir: /app
    ports:
        - 8080:8080
    volumes:
     - "./:/app"
     - "./logs:/root/.npm/_logs"
  redis:
    image: redis:5.0.4
    ports:
    - "6379:6379"
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: tiptop123
      MYSQL_DATABASE: ledger
      MYSQL_USER: ledger
      MYSQL_PASSWORD: tiptop123
    volumes:
    - "./data:/docker-entrypoint-initdb.d"
    - "db:/var/lib/mysql"
    command: --default-authentication-plugin=mysql_native_password
    ports:
    - "3306:3306"